import { Lot } from '../lot';

export const LOTS5: Lot[] = [
  {
    "url":"A1",
    "Name":"Block A Lot 1",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $105,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a1.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A2",
    "Name":"Block A Lot 2",
    "ForSale":"Completion date: May 1, 2019",
    "MLS":"https://matrix.ntreis.net/matrix/shared/26p9ZTjZW3/3845FM3364",
    "MLStext":"View this listing on MLS",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":" $349,900",
    "Acres":"1.00 acre",
    "SqFt":"2151 Square Feet",
    "BedBathGarage":"3 bed, 2.5 bath, 3 car",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/images/ca5/jeffersoniso.JPG','/assets/images/ca5/jeffersonfirst.jpg','/assets/images/ca5/jeffersonsecond.jpg','/assets/blacklines/ca5/a2.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A3",
    "Name":"Block A Lot 3",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $100,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a3.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A4",
    "Name":"Block A Lot 4",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $109,000",
    "Acres":"1.36 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a4.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A5",
    "Name":"Block A Lot 5",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $114,000",
    "Acres":"1.15 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a5.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A6",
    "Name":"Block A Lot 6",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $99,000",
    "Acres":"1.16 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a6.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A7",
    "Name":"Block A Lot 7",
    "ForSale":"lot for sale",
    "MLS":"https://matrix.ntreis.net/matrix/shared/mvz3C9dYW3/Lot7AFM3364",
    "MLStext":"View this listing on MLS",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $100,000",
    "Acres":"1.13 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a7.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A8",
    "Name":"Block A Lot 8",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $102,000",
    "Acres":"1.15 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a8.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A9",
    "Name":"Block A Lot 9",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $109,000",
    "Acres":"1.15 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a9.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A10",
    "Name":"Block A Lot 10",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $106,000",
    "Acres":"1.44 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a10.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A11",
    "Name":"Block A Lot 11",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $124,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a11.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A12",
    "Name":"Block A Lot 12",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":" $349,900",
    "Acres":"1.00 acre",
    "SqFt":"2151 Square Feet",
    "BedBathGarage":"3 bed, 2.5 bath, 3 car",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/images/ca5/jeffersoniso.JPG','/assets/images/ca5/jeffersonfirst.jpg','/assets/images/ca5/jeffersonsecond.jpg','/assets/blacklines/ca5/a12.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A13",
    "Name":"Block A Lot 13",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $104,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a13.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A14",
    "Name":"Block A Lot 14",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $102,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/a14.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B1",
    "Name":"Block B Lot 1",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $199,000","Acres":"2.79 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/b1.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B2",
    "Name":"Block B Lot 2",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $107,000",
    "Acres":"1.05 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/b2.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B3",
    "Name":"Block B Lot 3",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $107,000",
    "Acres":"1.05 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/b3.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B9",
    "Name":"Block B Lot 9",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $109,000",
    "Acres":"1.03 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/b9.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B19",
    "Name":"Block B Lot 19",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $115,000",
    "Acres":"1.09 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/b19.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B20",
    "Name":"Block B Lot 20",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $111,000",
    "Acres":"1.02 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/b20.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B21",
    "Name":"Block B Lot 21",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $113,000",
    "Acres":"1.06 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/b21.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B22",
    "Name":"Block B Lot 22",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $102,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/b22.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B23",
    "Name":"Block B Lot 23",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $102,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca5/b23.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.JPG','/assets/images/ca5/aerial2.JPG'],
    "BlankCell":"/"
  }
]
