import { Lot } from '../lot';

export const LOTS5: Lot[] = [
  {
    "url":"1535_Liberty_Lane",
    "Name":"1535 Liberty Lane",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $105,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a1.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3855_FM3364",
    "Name":"3855 FM 3364",
    "ForSale":"Completion date: May 1, 2019",
    "MLS":"https://matrix.ntreis.net/matrix/shared/26p9ZTjZW3/3845FM3364",
    "MLStext":"View this listing on MLS",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":" $349,900",
    "Acres":"1.00 acre",
    "SqFt":"2151 Square Feet",
    "BedBathGarage":"3 bed, 2.5 bath, 3 car",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a2.jpg','/assets/images/houses/Jefferson/Jefferson A front iso.jpg','/assets/images/houses/Jefferson/Jefferson A first floor iso.jpg','/assets/images/houses/Jefferson/Jefferson A first floor plan.jpg','/assets/images/houses/Jefferson/Jefferson A second floor iso.jpg','/assets/images/houses/Jefferson/Jefferson A second floor plan.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3881_FM3364",
    "Name":"3881 FM 3364",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $100,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a3.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3915_FM3364",
    "Name":"3915 FM 3364",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $109,000",
    "Acres":"1.36 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a4.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3963_FM3364",
    "Name":"3963 FM 3364",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $114,000",
    "Acres":"1.50 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a5.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3993_FM3364",
    "Name":"3993 FM 3364",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $99,000",
    "Acres":"1.15 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a6.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"454_CR770",
    "Name":"454 CR 770",
    "ForSale":"lot for sale",
    "MLS":"https://matrix.ntreis.net/matrix/shared/mvz3C9dYW3/Lot7AFM3364",
    "MLStext":"View this listing on MLS",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $100,000",
    "Acres":"1.19 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a7.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"4020_Independence_Way",
    "Name":"4020 Independence Way",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $102,000",
    "Acres":"1.16 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a8.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3980_Independence_Way",
    "Name":"3980 Independence Way",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $109,000",
    "Acres":"1.15 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a9.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3821_Independence_Way",
    "Name":"3821 Independence Way",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":" $349,900",
    "Acres":"1.15 acres",
    "SqFt":"2151 Square Feet",
    "BedBathGarage":"3 bed, 2.5 bath, 3 car",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a10.jpg','/assets/images/houses/Jefferson/Jefferson B.jpg','/assets/images/houses/Jefferson/Jefferson B left.jpg','/assets/images/houses/Jefferson/Jefferson B first floor.jpg','/assets/images/houses/Jefferson/Jefferson B second.jpg','/assets/images/houses/Jefferson/Jefferson B Floorplans-01.jpg','/assets/images/houses/Jefferson/Jefferson B Floorplans-02.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3910_Independence_Way",
    "Name":"3910 Independence Way",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $124,000",
    "Acres":"1.44 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a11.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3870_Independence_Way",
    "Name":"3870 Independence Way",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":" $349,900",
    "Acres":"1.21 acre",
    "SqFt":"2151 Square Feet",
    "BedBathGarage":"3 bed, 2.5 bath, 3 car",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a12.jpg','/assets/images/houses/Jefferson/Jefferson A front iso.jpg','/assets/images/houses/Jefferson/Jefferson A first floor iso.jpg','/assets/images/houses/Jefferson/Jefferson A first floor plan.jpg','/assets/images/houses/Jefferson/Jefferson A second floor iso.jpg','/assets/images/houses/Jefferson/Jefferson A second floor plan.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3840_Independence_Way",
    "Name":"3840 Independence Way",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $104,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a13.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3820_Independence_Way",
    "Name":"3820 Independence Way",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/a14.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"1590_Liberty_Lane",
    "Name":"1590 Liberty Lane",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $199,000",
    "Acres":"2.79 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b1.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"1616_Liberty_Lane",
    "Name":"1616 Liberty Lane",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $107,000",
    "Acres":"1.05 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b2.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"1650_Liberty_Lane",
    "Name":"1650 Liberty Lane",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.05 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b3.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"1676_Liberty_Lane",
    "Name":"1676 Liberty Lane",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.05 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b4.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1700_Liberty_Lane",
    "Name":"1700 Liberty Lane",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b5.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1710_Liberty_Lane",
    "Name":"1710 Liberty Lane",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.09 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b6.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1717_Liberty_Lane",
    "Name":"1717 Liberty Lane",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b7.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1711_Liberty_Lane",
    "Name":"1711 Liberty Lane",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.00 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b8.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3950_Independence_Way",
    "Name":"3950 Independence Way",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $109,000",
    "Acres":"1.03 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b9.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1660_Republic_Court",
    "Name":"1660 Republic Court",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b10.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1690_Republic_Court",
    "Name":"1690 Republic court",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b11.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1714_Republic_Court",
    "Name":"1714 Republic Court",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b12.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1715_Republic_Court",
    "Name":"1715 Republic Court",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.16 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b13.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1707_Republic_Court",
    "Name":"1707 Republic Court",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.15 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b14.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1691_Republic_Court",
    "Name":"1691 Republic Court",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b15.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1661_Republic_Court",
    "Name":"1661 Republic Court",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b16.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1660_Freedom_Court",
    "Name":"1660 Freedom Court",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b17.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },{
    "url":"1686_Freedom_Court",
    "Name":"1686 Freedom Court",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b18.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"1704_Freedom_Court",
    "Name":"1704 Freedom Court",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $115,000",
    "Acres":"1.06 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b19.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"1710_Freedom_Court",
    "Name":"1710 Freedom Court",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":" $349,900",
    "Acres":"1.02 acres",
    "SqFt":"2151 Square Feet",
    "BedBathGarage":"3 bed, 2.5 bath, 3 car",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/images/houses/Jefferson/Jefferson B.jpg','/assets/images/houses/Jefferson/Jefferson B left.jpg','/assets/images/houses/Jefferson/Jefferson B first floor.jpg','/assets/images/houses/Jefferson/Jefferson B second.jpg','/assets/images/houses/Jefferson/Jefferson B Floorplans-01.jpg','/assets/images/houses/Jefferson/Jefferson B Floorplans-02.jpg','/assets/blacklines/ca5/b20.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"1711_Freedom_Court",
    "Name":"1711 Freedom Court",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $113,000",
    "Acres":"1.12 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b21.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"1695_Freedom_Court",
    "Name":"1695 Freedom Court",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $102,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b22.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"1661_Freedom_Court",
    "Name":"1661 Freedom Court",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p style=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\">Bring Your Own Builder</p>",
    "Price":" $102,000",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"show",
    "CCR":"/assets/covenant-and-deed-restrictions.pdf",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca5/b23.jpg','/assets/blacklines/ca5/Final blackline.jpg','/assets/images/ca5/aerial1.jpg','/assets/images/ca5/aerial2.jpg'],
    "BlankCell":"/"
  }
]
