import { Lot } from '../lot';

export const LOTS8: Lot[] = [
  {
    "url":"1-1",
    "Name":"Lot 1-1",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.45 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-1.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-2",
    "Name":"Lot 1-2",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-2.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-3",
    "Name":"Lot 1-3",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-3.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-4",
    "Name":"Lot 1-4",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-4.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-5",
    "Name":"Lot 1-5",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-5.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-6",
    "Name":"Lot 1-6",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-6.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-7",
    "Name":"Lot 1-7",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-7.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-8",
    "Name":"Lot 1-8",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-8.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-9",
    "Name":"Lot 1-9",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-9.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-10",
    "Name":"Lot 1-10",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-10.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-11",
    "Name":"Lot 1-11",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-11.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-12",
    "Name":"Lot 1-12",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-12.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-13",
    "Name":"Lot 1-13",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-13.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-14",
    "Name":"Lot 1-14",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-14.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-15",
    "Name":"Lot 1-15",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-15.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-16",
    "Name":"Lot 1-16",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-16.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-17",
    "Name":"Lot 1-17",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-17.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-18",
    "Name":"Lot 1-18",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-18.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"1-19",
    "Name":"Lot 1-19",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.66 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/1-19.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"2-1",
    "Name":"Lot 2-1",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.06 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/2-1.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"2-2",
    "Name":"Lot 2-2",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.06 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/2-2.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"2-3",
    "Name":"Lot 2-3",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.06 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/2-3.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"2-4",
    "Name":"Lot 2-4",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.04 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/2-4.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"2-5",
    "Name":"Lot 2-5",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.04 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/2-5.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"2-6",
    "Name":"Lot 2-6",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.03 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/2-6.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"2-7",
    "Name":"Lot 2-7",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.17 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/2-7.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"2-8",
    "Name":"Lot 2-8",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.17 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/2-8.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"3-1",
    "Name":"Lot 3-1",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/3-1.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"3-2",
    "Name":"Lot 3-2",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/3-2.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"3-3",
    "Name":"Lot 3-3",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/3-3.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"3-4",
    "Name":"Lot 3-4",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/3-4.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"3-5",
    "Name":"Lot 3-5",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/3-5.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"3-6",
    "Name":"Lot 3-6",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/3-6.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"4-1",
    "Name":"Lot 4-1",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/4-1.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"4-2",
    "Name":"Lot 4-2",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/4-2.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"4-3",
    "Name":"Lot 4-3",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/4-3.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"4-4",
    "Name":"Lot 4-4",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/4-4.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"4-5",
    "Name":"Lot 4-5",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/4-5.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"4-6",
    "Name":"Lot 4-6",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/4-6.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"5-1",
    "Name":"Lot 5-1",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/5-1.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"5-2",
    "Name":"Lot 5-2",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/5-2.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"5-3",
    "Name":"Lot 5-3",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/5-3.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"5-4",
    "Name":"Lot 5-4",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/5-4.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"5-5",
    "Name":"Lot 5-5",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/5-5.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"5-6",
    "Name":"Lot 5-6",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $209,900",
    "Acres":"1.00 acre",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca8/5-6.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/Absolute Value with Opt.png','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/Choice with Opt.png','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/PT-78 colored floorplan.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/Sundowner with Opt.png','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca8/ca8 blackline.JPG'],
    "BlankCell":"/"
  }
]
