import { Lot } from '../lot';

export const LOTS9: Lot[] = [
  {
    "url":"1",
    "Name":"Lot 1",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/1.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"2",
    "Name":"Lot 2",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/2.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3",
    "Name":"Lot 3",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/3.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"4",
    "Name":"Lot 4",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/4.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"5",
    "Name":"Lot 5",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/5.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"6",
    "Name":"Lot 6",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/6.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"7",
    "Name":"Lot 7",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/7.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"8",
    "Name":"Lot 8",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/8.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"9",
    "Name":"Lot 9",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/9.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"10",
    "Name":"Lot 10",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/10.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"11",
    "Name":"Lot 11",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/11.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"12",
    "Name":"Lot 12",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/12.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"13",
    "Name":"Lot 13",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/13.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"14",
    "Name":"Lot 14",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/14.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"15",
    "Name":"Lot 15",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/15.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"16",
    "Name":"Lot 16",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/16.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"17",
    "Name":"Lot 17",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/17.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"18",
    "Name":"Lot 18",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/18.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"19",
    "Name":"Lot 19",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/19.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"20",
    "Name":"Lot 20",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/20.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"21",
    "Name":"Lot 21",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/21.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"22",
    "Name":"Lot 22",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/22.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"23",
    "Name":"Lot 23",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/23.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"24",
    "Name":"Lot 24",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/24.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"25",
    "Name":"Lot 25",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/25.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"26",
    "Name":"Lot 26",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/26.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"27",
    "Name":"Lot 27",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/27.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"28",
    "Name":"Lot 28",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/28.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"29",
    "Name":"Lot 29",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/29.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"30",
    "Name":"Lot 30",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/30.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"31",
    "Name":"Lot 31",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/31.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"32",
    "Name":"Lot 32",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/32.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"33",
    "Name":"Lot 33",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/33.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"34",
    "Name":"Lot 34",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/34.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"35",
    "Name":"Lot 35",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/35.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"36",
    "Name":"Lot 36",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/36.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"37",
    "Name":"Lot 37",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/37.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"38",
    "Name":"Lot 38",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/38.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"39",
    "Name":"Lot 39",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/39.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"40",
    "Name":"Lot 40",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/40.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"41",
    "Name":"Lot 41",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/41.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"42",
    "Name":"Lot 42",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/42.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"43",
    "Name":"Lot 43",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/43.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"44",
    "Name":"Lot 44",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/44.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"45",
    "Name":"Lot 45",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/45.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"46",
    "Name":"Lot 46",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/46.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"47",
    "Name":"Lot 47",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/47.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"48",
    "Name":"Lot 48",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/48.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"49",
    "Name":"Lot 49",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/49.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"50",
    "Name":"Lot 50",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/50.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"51",
    "Name":"Lot 51",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/51.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"52",
    "Name":"Lot 52",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/52.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"53",
    "Name":"Lot 53",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/53.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"54",
    "Name":"Lot 54",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/54.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"55",
    "Name":"Lot 55",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/55.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"56",
    "Name":"Lot 56",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/56.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"57",
    "Name":"Lot 57",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/57.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"58",
    "Name":"Lot 58",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/58.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"59",
    "Name":"Lot 59",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/59.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"60",
    "Name":"Lot 60",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/60.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"61",
    "Name":"Lot 61",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/61.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"62",
    "Name":"Lot 62",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/62.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"63",
    "Name":"Lot 63",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/63.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"64",
    "Name":"Lot 64",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/64.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"65",
    "Name":"Lot 65",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/65.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"66",
    "Name":"Lot 66",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/66.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"67",
    "Name":"Lot 67",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/67.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"68",
    "Name":"Lot 68",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/68.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"69",
    "Name":"Lot 69",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/69.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"70",
    "Name":"Lot 70",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/70.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"71",
    "Name":"Lot 71",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/71.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"72",
    "Name":"Lot 72",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/72.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"73",
    "Name":"Lot 73",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/73.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"74",
    "Name":"Lot 74",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/74.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"75",
    "Name":"Lot 75",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/75.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"76",
    "Name":"Lot 76",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/76.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"77",
    "Name":"Lot 77",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/77.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"78",
    "Name":"Lot 78",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/78.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"79",
    "Name":"Lot 79",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/79.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"80",
    "Name":"Lot 80",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/80.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"81",
    "Name":"Lot 81",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/81.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"82",
    "Name":"Lot 82",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/82.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"83",
    "Name":"Lot 83",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/83.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"84",
    "Name":"Lot 84",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/84.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"85",
    "Name":"Lot 85",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/85.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"86",
    "Name":"Lot 86",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/86.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"87",
    "Name":"Lot 87",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/87.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"88",
    "Name":"Lot 88",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/88.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"89",
    "Name":"Lot 89",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/89.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"90",
    "Name":"Lot 90",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/90.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"91",
    "Name":"Lot 91",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/91.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"92",
    "Name":"Lot 92",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/92.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"93",
    "Name":"Lot 93",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/93.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"94",
    "Name":"Lot 94",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/94.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"95",
    "Name":"Lot 95",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/95.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"96",
    "Name":"Lot 96",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/96.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"97",
    "Name":"Lot 97",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/97.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"98",
    "Name":"Lot 98",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/98.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"99",
    "Name":"Lot 99",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/99.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"100",
    "Name":"Lot 100",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/100.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"101",
    "Name":"Lot 101",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca9/101.JPG','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca9/ca9 black line.jpg'],
    "BlankCell":"/"
  }
]
