import { Lot } from '../lot';

export const LOTS3: Lot[] = [
  {
    "url":"A1",
    "Name":"Block A Lot 1",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a1.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A2",
    "Name":"Block A Lot 2",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a2.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A3",
    "Name":"Block A Lot 3",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a3.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A4",
    "Name":"Block A Lot 4",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a4.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A5",
    "Name":"Block A Lot 5",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a5.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A6",
    "Name":"Block A Lot 6",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a6.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A7",
    "Name":"Block A Lot 7",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a7.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A8",
    "Name":"Block A Lot 8",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a8.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A9",
    "Name":"Block A Lot 9",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a9.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A10",
    "Name":"Block A Lot 10",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a10.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A11",
    "Name":"Block A Lot 11",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a11.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A12",
    "Name":"Block A Lot 12",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a12.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A13",
    "Name":"Block A Lot 13",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a13.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A14",
    "Name":"Block A Lot 14",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a14.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A15",
    "Name":"Block A Lot 15",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a15.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A16",
    "Name":"Block A Lot 16",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a16.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A17",
    "Name":"Block A Lot 17",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a17.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A18",
    "Name":"Block A Lot 18",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a18.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A19",
    "Name":"Block A Lot 19",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a19.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A20",
    "Name":"Block A Lot 20",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a20.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A21",
    "Name":"Block A Lot 21",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a21.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A22",
    "Name":"Block A Lot 22",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a22.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A23",
    "Name":"Block A Lot 23",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a23.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A24",
    "Name":"Block A Lot 24",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a24.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A25",
    "Name":"Block A Lot 25",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a25.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A26",
    "Name":"Block A Lot 26",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a26.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A27",
    "Name":"Block A Lot 27",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a27.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A28",
    "Name":"Block A Lot 28",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a28.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A29",
    "Name":"Block A Lot 29",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a29.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A30",
    "Name":"Block A Lot 30",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a30.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A31",
    "Name":"Block A Lot 31",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a31.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A32",
    "Name":"Block A Lot 32",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a32.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A33",
    "Name":"Block A Lot 33",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a33.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A34",
    "Name":"Block A Lot 34",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a34.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"A35",
    "Name":"Block A Lot 35",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot a35.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B1",
    "Name":"Block B Lot 1",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b1.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B2",
    "Name":"Block B Lot 2",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b2.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B3",
    "Name":"Block B Lot 3",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b3.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B4",
    "Name":"Block B Lot 4",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b4.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B5",
    "Name":"Block B Lot 5",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b5.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B6",
    "Name":"Block B Lot 6",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b6.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B7",
    "Name":"Block B Lot 7",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b7.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B8",
    "Name":"Block B Lot 8",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b8.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B9",
    "Name":"Block B Lot 9",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b9.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B10",
    "Name":"Block B Lot 10",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b10.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B11",
    "Name":"Block B Lot 11",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b11.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B12",
    "Name":"Block B Lot 12",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b12.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B13",
    "Name":"Block B Lot 13",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b13.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B14",
    "Name":"Block B Lot 14",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b14.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B15",
    "Name":"Block B Lot 15",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b15.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B16",
    "Name":"Block B Lot 16",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b16.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B17",
    "Name":"Block B Lot 17",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b17.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B18",
    "Name":"Block B Lot 18",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b18.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B19",
    "Name":"Block B Lot 19",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b19.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B20",
    "Name":"Block B Lot 20",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b20.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B21",
    "Name":"Block B Lot 21",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b21.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B22",
    "Name":"Block B Lot 22",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b22.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B23",
    "Name":"Block B Lot 23",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b23.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B24",
    "Name":"Block B Lot 24",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b24.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B25",
    "Name":"Block B Lot 25",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b25.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B26",
    "Name":"Block B Lot 26",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b26.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B27",
    "Name":"Block B Lot 27",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b27.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B28",
    "Name":"Block B Lot 28",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b28.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B29",
    "Name":"Block B Lot 29",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b29.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B30",
    "Name":"Block B Lot 30",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b30.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B31",
    "Name":"Block B Lot 31",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b31.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B32",
    "Name":"Block B Lot 32",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b32.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B33",
    "Name":"Block B Lot 33",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b33.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B34",
    "Name":"Block B Lot 34",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b34.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B35",
    "Name":"Block B Lot 35",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b35.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"B36",
    "Name":"Block B Lot 36",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot b36.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C1",
    "Name":"Block C Lot 1",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C1.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C2",
    "Name":"Block C Lot 2",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C2.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C3",
    "Name":"Block C Lot 3",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C3.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C4",
    "Name":"Block C Lot 4",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C4.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C5",
    "Name":"Block C Lot 5",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C5.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C6",
    "Name":"Block C Lot 6",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C6.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C7",
    "Name":"Block C Lot 7",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C7.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C8",
    "Name":"Block C Lot 8",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C8.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C9",
    "Name":"Block C Lot 9",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C9.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C10",
    "Name":"Block C Lot 10",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C10.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C11",
    "Name":"Block C Lot 11",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C11.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C12",
    "Name":"Block C Lot 12",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C12.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C13",
    "Name":"Block C Lot 13",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C13.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C14",
    "Name":"Block C Lot 14",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C14.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C15",
    "Name":"Block C Lot 15",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C15.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"C16",
    "Name":"Block C Lot 16",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca3/lot C16.jpg','/assets/blacklines/ca3/ca3blackline.JPG'],
    "BlankCell":"/"
  }
]
