import { Lot } from '../lot';

export const LOTS1: Lot[] = [
  {
    "url":"1",
    "Name":"Lot 1",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"5.00 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca1/lot 1.JPG','/assets/blacklines/ca1/ca1blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"2",
    "Name":"Lot 2",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.98 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca1/lot 2.JPG','/assets/blacklines/ca1/ca1blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"3",
    "Name":"Lot 3",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca1/lot 3.JPG','/assets/blacklines/ca1/ca1blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"4",
    "Name":"Lot 4",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca1/lot 4.JPG','/assets/blacklines/ca1/ca1blackline.JPG'],
    "BlankCell":"/"
  }
]
