import { Lot } from '../lot';

export const LOTS2: Lot[] = [
  {
    "url":"1",
    "Name":"Lot 1",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.06 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 1.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"2",
    "Name":"Lot 2",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 2.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3",
    "Name":"Lot 3",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.01 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 3.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"4",
    "Name":"Lot 4",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.06 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 4.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"5",
    "Name":"Lot 5",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 5.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"6",
    "Name":"Lot 6",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 6.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"7",
    "Name":"Lot 7",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 7.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"8",
    "Name":"Lot 8",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 8.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"9",
    "Name":"Lot 9",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 9.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"10",
    "Name":"Lot 10",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 10.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"11",
    "Name":"Lot 11",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 11.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"12",
    "Name":"Lot 12",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 12.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"13",
    "Name":"Lot 13",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 13.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"14",
    "Name":"Lot 14",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.21 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 14.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"15",
    "Name":"Lot 15",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"2.66 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 15.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"16",
    "Name":"Lot 16",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.42 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 16.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"17",
    "Name":"Lot 17",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.33 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 17.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"18",
    "Name":"Lot 18",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"3.13 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 18.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"19",
    "Name":"Lot 19",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.09 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 19.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"20",
    "Name":"Lot 20",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.02 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 20.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"21",
    "Name":"Lot 21",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 21.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"22",
    "Name":"Lot 22",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 22.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"23",
    "Name":"Lot 23",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.04 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 23.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"24",
    "Name":"Lot 24",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.04 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 24.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"25",
    "Name":"Lot 25",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 25.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"26",
    "Name":"Lot 26",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 26.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"27",
    "Name":"Lot 27",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 27.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"28",
    "Name":"Lot 28",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 28.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"29",
    "Name":"Lot 29",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.04 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 29.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"30",
    "Name":"Lot 30",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.19 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 30.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"31",
    "Name":"Lot 31",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"1.17 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925641,
    "Images":['/assets/blacklines/ca2/lot 31.jpg','/assets/blacklines/ca2/ca2blackline.jpg'],
    "BlankCell":"/"
  }
]
