import { Lot } from '../lot';

export const LOTS7: Lot[] = [
  {
    "url":"37",
    "Name":"Lot 37",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.11 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/37.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"38",
    "Name":"Lot 38",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"1.02 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/38.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"39",
    "Name":"Lot 39",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/39.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"40",
    "Name":"Lot 40",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/40.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"41",
    "Name":"Lot 41",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.01 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/41.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"42",
    "Name":"Lot 42",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.63 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/42.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"43",
    "Name":"Lot 43",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.08 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/43.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"44",
    "Name":"Lot 44",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/44.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"45",
    "Name":"Lot 45",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/45.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"46",
    "Name":"Lot 46",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/46.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"47",
    "Name":"Lot 47",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/47.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"48",
    "Name":"Lot 48",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/48.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"49",
    "Name":"Lot 49",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/49.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"50",
    "Name":"Lot 50",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/50.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"51",
    "Name":"Lot 51",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/51.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"52",
    "Name":"Lot 52",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/52.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"53",
    "Name":"Lot 53",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/53.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"54",
    "Name":"Lot 54",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/54.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"55",
    "Name":"Lot 55",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/55.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"56",
    "Name":"Lot 56",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/56.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"57",
    "Name":"Lot 57",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/57.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"58",
    "Name":"Lot 58",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/58.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"59",
    "Name":"Lot 59",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/59.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"60",
    "Name":"Lot 60",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.97 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/60.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"61",
    "Name":"Lot 61",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/61.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"62",
    "Name":"Lot 62",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/62.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"63",
    "Name":"Lot 63",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"2.09 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/63.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"64",
    "Name":"Lot 64",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.62 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/64.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"65",
    "Name":"Lot 65",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/65.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"66",
    "Name":"Lot 66",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/66.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"67",
    "Name":"Lot 67",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.51 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/67.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"68",
    "Name":"Lot 68",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.62 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/68.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"69",
    "Name":"Lot 69",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/69.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"70",
    "Name":"Lot 70",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/70.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"71",
    "Name":"Lot 71",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/71.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"72",
    "Name":"Lot 72",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/72.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"73",
    "Name":"Lot 73",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/73.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"74",
    "Name":"Lot 74",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/74.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"75",
    "Name":"Lot 75",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/75.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"76",
    "Name":"Lot 76",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/76.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"77",
    "Name":"Lot 77",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/77.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"78",
    "Name":"Lot 78",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/78.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"79",
    "Name":"Lot 79",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/79.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"80",
    "Name":"Lot 80",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/80.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"81",
    "Name":"Lot 81",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/81.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"82",
    "Name":"Lot 82",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/82.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"83",
    "Name":"Lot 83",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/83.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"84",
    "Name":"Lot 84",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/84.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"85",
    "Name":"Lot 85",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/85.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"86",
    "Name":"Lot 86",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/86.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"87",
    "Name":"Lot 87",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/87.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"88",
    "Name":"Lot 88",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.02 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/88.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"89",
    "Name":"Lot 89",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.11 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/89.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"90",
    "Name":"Lot 90",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.11 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/90.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"91",
    "Name":"Lot 91",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.08 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/91.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"92",
    "Name":"Lot 92",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.09 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/92.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"93",
    "Name":"Lot 93",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.09 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/93.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"94",
    "Name":"Lot 94",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.10 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/94.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"95",
    "Name":"Lot 95",
    "ForSale":"SOLD",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"",
    "Acres":"1.50 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/95.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"96",
    "Name":"Lot 96",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.78 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/96.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"97",
    "Name":"Lot 97",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.77 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/97.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"98",
    "Name":"Lot 98",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.46 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/98.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"99",
    "Name":"Lot 99",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.07 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/99.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"100",
    "Name":"Lot 100",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.07 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/100.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"101",
    "Name":"Lot 101",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.07 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/101.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"102",
    "Name":"Lot 102",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.07 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/102.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  },
  {
    "url":"103",
    "Name":"Lot 103",
    "ForSale":"home for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<img src='/assets/images/logos/copehomes.png'>",
    "Price":"from $189,900",
    "Acres":"1.11 acres",
    "SqFt":"1,475 - 2,001 Square Feet",
    "BedBathGarage":"3-5 bed, 2 bath",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Jose Espitia",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2144257840,
    "Images":['/assets/blacklines/ca7/103.jpg','/assets/images/ca7/absolute value.jpg','/assets/images/ca7/WilliamsburgFP.jpg','/assets/images/ca7/dining den 2.jpg','/assets/images/ca7/Choice.jpg','/assets/images/ca7/ConcordFP.jpg','/assets/images/ca7/den dining.jpg','/assets/images/ca7/pt-78.png','/assets/images/ca7/DeerfieldFP.jpg','/assets/images/ca7/living kitchen 2.jpg','/assets/images/ca7/Sundowner.jpg','/assets/images/ca7/RichmondFP.jpg','/assets/images/ca7/kitchen dining.jpg','/assets/blacklines/ca7/CA7 black line.png'],
    "BlankCell":"/"
  }
]
