import { Lot } from '../lot';

export const LOTS4: Lot[] = [
  {
    "url":"1",
    "Name":"Lot 1",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"Retail pad sites available",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca4/ca4blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"2",
    "Name":"Lot 2",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"318 luxury apartments",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/images/ca4/perspective 1.jpg','/assets/images/ca4/perspective 2.jpg','/assets/images/ca4/perspective 3.jpg','/assets/blacklines/ca4/ca4blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"3",
    "Name":"Lot 3",
    "ForSale":"lot for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"Retail pad sites available",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca4/ca4blackline.jpg'],
    "BlankCell":"/"
  },
  {
    "url":"4",
    "Name":"Lot 4",
    "ForSale":"for sale",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"Retail pad sites available",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca4/ca4blackline.jpg'],
    "BlankCell":"/"
  }
]
