import { Lot } from '../lot';

export const LOTS6: Lot[] = [
  {
    "url":"1",
    "Name":"Lot 1",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"5.00 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca6/lot 6.JPG','/assets/blacklines/ca6/ca6blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"2",
    "Name":"Lot 2",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"6.98 acres",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca6/lot 2.JPG','/assets/blacklines/ca6/ca6blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"3",
    "Name":"Lot 3",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"6.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca6/lot 3.JPG','/assets/blacklines/ca6/ca6blackline.JPG'],
    "BlankCell":"/"
  },
  {
    "url":"4",
    "Name":"Lot 4",
    "ForSale":"lot sold",
    "MLS":"",
    "MLStext":"",
    "Builder":"<p Class=\"font-size: 3vw; margin: 0px; margin-bottom: 2vh;\"></p>",
    "Price":"",
    "Acres":"6.00 acre",
    "SqFt":"",
    "BedBathGarage":"",
    "Class":"hide",
    "CCR":"",
    "ContactName":"Mark Cope",
    "ContactEmail":"sales@copedfw.com",
    "ContactPhone":2145925642,
    "Images":['/assets/blacklines/ca6/lot 4.JPG','/assets/blacklines/ca6/ca6blackline.JPG'],
    "BlankCell":"/"
  }
]
